- name: Ensure dnsmasq
  ansible.builtin.package:
    name:
      - dnsmasq
    state: present
  become: true

- name: Ensure dnsmasq ocp-config
  ansible.builtin.template:
    dest: /etc/dnsmasq.d/dnsmasq-ocp.conf
    src: dnsmasq-ocp.conf.j2
    mode: '0640'
    owner: root
    group: dnsmasq
  notify: Restart dnsmasq
  become: true

- name: Set listen-address in dnsmasq config
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^listen-address='
    line: "listen-address={{ ansible_default_ipv4.address }}"
    mode: '0640'
    owner: root
    group: dnsmasq
    state: present
    create: true
  notify: Restart dnsmasq
  become: true

- name: Ensure enable and start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
  become: true
