- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - nmstate
    state: present
  tags:
    - packages

- name: Ensure ocp_tools directory
  become: true
  ansible.builtin.file:
    state: directory
    name: "{{ item }}"
    mode: '0700'
    owner: "{{ mirror_data_dir_group }}"
    group: "{{ mirror_data_dir_owner }}"
  loop:
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry"
    - "{{ mirror_registry_cert_dir }}"
    - "{{ mirror_data_dir }}"
    - "{{ config_path }}"
  tags:
    - packages

- name: Print download urls for debugging
  ansible.builtin.debug:
    msg: '{{ item }}'
  loop:
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/oc-mirror.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux-{{ ocp_version }}.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux-{{ ocp_version }}.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/{{ mirror_registry_version }}/mirror-registry.tar.gz"
  tags:
    - never
    - debug


- name: Download client tools
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/."
  loop:
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/oc-mirror.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux-{{ ocp_version }}.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux-{{ ocp_version }}.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/{{ mirror_registry_version }}/mirror-registry.tar.gz"
  tags:
    - packages

- name: extract client tools
  ansible.builtin.unarchive:
    src: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/{{ item.tar }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/{{ item.bin }}"
  loop:
    - tar: oc-mirror.tar.gz
      bin: oc-mirror
    - tar: "openshift-client-linux-{{ ocp_version }}.tar.gz"
      bin: oc
    - tar: "openshift-install-linux-{{ ocp_version }}.tar.gz"
      bin: openshift-install
  tags:
    - packages

- name: Extract mirror-registry
  ansible.builtin.unarchive:
    src: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry.tar.gz"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry"
  tags:
    - packages
    - registry
  when: install_registry is true

- name: eEnsure execution permissions
  ansible.builtin.file:
    state: file
    mode: '0755'
    name: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/{{ item }}"
  loop:
    - kubectl
    - oc-mirror
    - openshift-install
    - oc
  tags:
    - packages
