- name: Upload RHEL image to OpenStack
  openstack.cloud.image:
    cloud: default
    name: rhel-9.5-x86_64
    filename: "{{ rhel_image_path }}"
    container_format: bare
    disk_format: qcow2

- name: Create a new OpenStack keypair
  openstack.cloud.keypair:
    cloud: default
    name: "{{ os_keypair_name }}"
    public_key_file: "{{ os_keypair_pubkey_path }}"
  register: keypair
  ignore_errors: true

- name: Create mirror volume
  openstack.cloud.volume:
    cloud: default
    display_name: mirror-volume
    size: 1000
    volume_type: luks-aes-xts-plain64
    availability_zone: nova
    state: present
  register: mirror_volume

#- name: create bastion host
#  openstack.cloud.server:
