- name: Ensure control server group
  openstack.cloud.server_group:
    cloud: default
    state: present
    name: '{{ os_ocp_control_server_group_name }}'
    policy: anti-affinity
  register: control_group

- name: Ensure compute server group
  openstack.cloud.server_group:
    cloud: default
    state: present
    name: '{{ os_ocp_compute_server_group_name }}'
    policy: anti-affinity
  register: compute_group

- name: Upload agent-ISO image to OpenStack
  openstack.cloud.image:
    name: "{{ os_ocp_agent_image_name }}"
    filename: "{{ os_ocp_agent_image_path }}"
    disk_format: iso
    container_format: bare
    state: present
  tags:
    - never

- name: Create volumes for all nodes
  openstack.cloud.volume:
    name: "{{ item.name }}-volume"
    size: 100
    state: present
  loop: "{{ ocp_machines }}"

- name: Create ocp servers
  openstack.cloud.server:
    name: "{{ item.name }}"
    auto_ip: false
    image: "{{ os_ocp_agent_image_name }}"
    flavor: "{{ os_ocp_controlplane_flavor if item.name.startswith('control') else os_ocp_compute_flavor }}"
    security_groups: [ocp-nodes]
    volumes:
      - "{{ item.name }}-volume"
    nics:
      - port-name: "{{ item.name }}"
    scheduler_hints:
      group: "{{ control_group.server_group.id if item.name.startswith('control') else compute_group.server_group.id }}"
    wait: true
    state: present
  loop: "{{ ocp_machines }}"
