- name: ensure dnsmasq
  ansible.builtin.package:
    name:
      - dnsmasq
    state: present
  become: true

- name: Ensure dnsmasq custom DNS entries for ocp nodes are present
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/dnsmasq-ocp.conf
    line: "address=/{{ item.name }}.{{ ocp_base_domain }}/{{ item.ip }}"
    create: true
    state: present
  loop: "{{ ocp_machines }}"
  notify: Restart dnsmasq
  become: true

- name: ensure registry and vip dns entries
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/dnsmasq-ocp.conf
    line: "address=/{{ item.name }}/{{ item.ip }}"
    create: true
    state: present
  loop:
    - name: '{{ mirror_registry_hostname }}'
      ip: '{{ mirror_registry_ip }}'
    - name: 'api.{{ ocp_cluster_name }}.{{ ocp_base_domain }}'
      ip: '{{ ocp_api_vip }}'
    - name: '.apps.{{ ocp_cluster_name }}.{{ ocp_base_domain }}'
      ip: '{{ ocp_ingress_vip }}'
  notify: Restart dnsmasq
  become: true

- name: Set listen-address in dnsmasq config
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^listen-address='
    line: "listen-address={{ ansible_default_ipv4.address }}"
    state: present
    create: yes
  notify: Restart dnsmasq
  become: true

- name: enable and start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
  become: true