- name: ensure control server group
  openstack.cloud.server_group:
    cloud: default
    state: present
    name: '{{ os_ocp_control_server_group_name }}'
    policy: anti-affinity

- name: ensure compute server group
  openstack.cloud.server_group:
    cloud: default
    state: present
    name: '{{ os_ocp_compute_server_group_name }}'
    policy: anti-affinity

- name: Upload agent-ISO image to OpenStack
  openstack.cloud.image:
    name: "{{ os_ocp_agent_image_name }}"
    filename: "{{ os_ocp_agent_image_path }}"
    disk_format: iso
    container_format: bare
    state: present

- name: Get image details
  openstack.cloud.image_info:
    name: "{{ os_ocp_agent_image_name }}"
  register: ocp_image_info

- name: Create volumes for all nodes
  openstack.cloud.volume:
    name: "{{ item.name }}-volume"
    size: 100
    state: present
  loop: "{{ ocp_machines }}"

- name: Create ocp servers
  openstack.cloud.server:
    name: "{{ item.name }}"
    image: "{{ ocp_image_info.openstack_images[0].id }}"
    flavor: "{{ os_ocp_controlplane_flavor if item.name.startswith('control') else os_ocp_compute_flavor }}"
    security_groups: [ocp-nodes]
    boot_volume: "{{ item.name }}-volume"
    network:
      port: "{{ item.name }}"
    server_group: "{{ os_ocp_control_server_group_name if item.name.startswith('control') else os_ocp_compute_server_group_name }}"
    wait: yes
    state: present
  loop: "{{ ocp_machines }}"